/**
 * Created by yichizhang on 15/7/26.
 */

export default {
  INCREMENT_COUNTER1: 'INCREMENT_COUNTER1',
  INCREMENT_COUNTER2: 'INCREMENT_COUNTER2',
  DECREMENT_COUNTER1: 'DECREMENT_COUNTER1',
  DECREMENT_COUNTER2: 'DECREMENT_COUNTER12',
};

